data_path: dataset/train.csv
experiment_name: model-monitors
model_params:
  criterion: gini
  max_depth: 7
  max_features: sqrt
  min_samples_leaf: 4
  min_samples_split: 6
  model_type: DecisionTreeClassifier
random_state: 42
target_column: loan_paid_back
test_size: 0.9
tracking_uri: http://54.236.35.141:5000/
